sudo: required
services:
  - docker

before_install:
  - docker build -t manpreetdhindsa/docker-react -f Dockerfile.dev .

script:
  - docker run manpreetdhindsa/docker-react npm run test -- -- coverage